[package]
name = "ch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
koto = "0.8.1"
parking_lot = "0.11.2"
